# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.configuration-cache=true
kotlin.code.style=official

# 将 Gradle 依赖下载路径改到 F 盘
org.gradle.user.home=./.gradle_home

# 设置 Gradle 使用 F 盘中的 JDK 11 进行编译任务
org.gradle.java.installations.paths=F\\:/nicecode/jdk-11/jdk-11.0.24+8
# 移除之前的 daemon java home，让 it use the default (21)
# org.gradle.java.home=F\:/nicecode/jdk-11/jdk-11.0.24+8

android.disallowKotlinSourceSets=false
# 使用 KSP2
ksp.useKSP2=true
